config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]

pages/urls.py
from django.urls import path, include
from .views import HomePageView, ListView, DataVizView
from . import views
from django.contrib import admin

urlpatterns = [
   #path("<int:id>", views.index, name="index"),
    path('', HomePageView.as_view(), name='home'),
    path("create/", views.create.as_view(), name='create'),
    path('list/', ListView.as_view(), name='list'),
    path('dataviz/', DataVizView.as_view(), name='dataviz'),
    path('admin/',admin.site.urls)
]

pages/models.py
from django.db import models

class User(models.Model):
    Company_Name = models.CharField(max_length=200)
    Initial_Loan_Amount = models.FloatField()
    Initial_Interest_Rate = models.FloatField()
    Loan_Rate_After_Default = models.FloatField()
    Loan_Duration = models.FloatField()
    Final_Loan_Amount = models.FloatField()
    Overall_Rating = models.FloatField()

    def get_absolute_url(self):
        return u'/list/' 

pages/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
from django.db.models import Sum, Avg
from django.views import generic
from django.views.generic.edit import CreateView

class HomePageView(generic.TemplateView):
    template_name="home.html"

class ListView(generic.ListView):
    model = models.User
    template_name="main/list.html"

class DataVizView(generic.ListView):
    model = models.User
    template_name="main/dataviz.html"
    def get_context_data(self, **kwargs):
        context = super(DataVizView, self).get_context_data(**kwargs)
        # context['Loan_Rate_After_Default_sum'] = models.User.objects.all().aggregate(sum_all=Sum('Loan_Rate_After_Default')).get('sum_all')
        context['Loan_Rate_After_Default_sum'] = models.User.objects.all().aggregate(Sum('Loan_Rate_After_Default'))
        context['Initial_Interest_Rate_average'] = models.User.objects.all().aggregate(Avg('Initial_Interest_Rate'))
        return context

 



# SELECT AVG(Initial_Loan_Amount)
# Initial_Interest_Rate

# Loan_Duration 
# Final_Loan_Amount 
# Overall_Rating 
    
        # def get_queryset(self):
        #     return Project.objects

# def index(response, id):
#         ls = ToDoList.objects.get(id=id)
#         return render(response,"main/list.html",{"ls":ls})

# def home(response):
#     return render(response, "main/home.html",{})

class create(CreateView): 
    model = models.User
    template_name = "main/create.html"
    fields = ["Company_Name", "Initial_Loan_Amount", "Initial_Interest_Rate", 
    "Loan_Rate_After_Default", "Loan_Duration", "Final_Loan_Amount", "Overall_Rating"]

    
  

pages/templates/home.html
<h1> Welcome to Shylock!</h1>

pages/templates/main/base.html
<html>
    <head>
        <title> {%block title %} Loan Shark Attack {% endblock %} </title>
    </head>

    <body>
        <div id="content", name="content">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

pages/templates/main/create.html
{% extends 'main/base.html'%}

{% block title %} Create New List {% endblock %}

{% block content %} 
Create Page 
<form method = "post" action="/create/">
    {% csrf_token%}
    {{form.as_p}}
    <button type="submit", name="save">Create New</button>
    <button type = "submit", name = "save", value = "save">Save</button>
    </form>
{% endblock %}

pages/templates/main/dataviz.html
<h1>Data Viz</h1>
{{Loan_Rate_After_Default_sum}}

<h1>Data Viz</h1>
{{Initial_Interest_Rate_average}}



{% for user in user_list %}
<ul>
    <li>Initial Loan Amount: {{user.Initial_Loan_Amount}}</li> 
    <li>Initial Interest Rate: {{user.Initial_Interest_Rate}}</li>
    <li>Loan Rate After Default: {{user.Loan_Rate_After_Default}}</li>
    <li>Loan Duration: {{user.Loan_Duration}}</li>
    <li>User Final Loan Amount: {{user.Final_Loan_Amount}}</li>
    <li>Overall Rating: {{user.Overall_Rating}} </li>
</ul>
    <!-- <li><a href="#">Test</a></li> -->
{% endfor %}

end of list